//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetMir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_number { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public int ID_item { get; set; }
        public Nullable<int> ID_client { get; set; }
        public int code_to_get { get; set; }
        public string status { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual Users Users { get; set; }
        public virtual OrderComposition OrderComposition { get; set; }
    }
}
