//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetMir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderComposition = new HashSet<OrderComposition>();
            this.Placement = new HashSet<Placement>();
        }
    
        public string article_number { get; set; }
        public string name { get; set; }
        public string unit { get; set; }
        public Nullable<float> stoimost { get; set; }
        public Nullable<float> max_discount { get; set; }
        public Nullable<int> manufacturer2 { get; set; }
        public Nullable<int> provider2 { get; set; }
        public Nullable<int> category_number { get; set; }
        public Nullable<float> discount { get; set; }
        public Nullable<int> quantity_in_stock { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderComposition> OrderComposition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Placement> Placement { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
